### ISSUE TITLE
Unable to turn off Alarm Switch

### ISSUE THREAD

**Issue by ahmadnazirafiq** [hdmvide/Homebridge-SwitchSound#1]
I've set up an automation to turn alarm switch on if the Alarm was triggered. However, I can't turn the alarm switch off, and it even brings down my entire homebridge. Here's the log:

[06/01/2021, 15:15:26] [SwitchSound] Stopping Sound.... 
[06/01/2021, 15:15:27] TypeError: currentSwitch.playProcess.kill is not a function
    at SwitchSoundPlatform.setPowerState (/usr/local/lib/node_modules/homebridge-switchsound/index.js:263:35)
    at Characteristic.emit (events.js:315:20)
    at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:652:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1461:24
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1303:10)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:812:12)
[06/01/2021, 15:15:27] Got SIGTERM, shutting down Homebridge...

**Comment by hdmvide** [comment]
Hi,
does it always happen? If you turn on and turn off contextually from HomeKit what happens?

To be able to understand the problem you should:

1. Send me the switch configuration
2. Enabling the plugin debug parameter, executing a test and send me the debug log.

**Comment by hdmvide** [comment]
> I've set up an automation to turn alarm switch on if the Alarm was triggered. However, I can't turn the alarm switch off, and it even brings down my entire homebridge. Here's the log:
> 
> [06/01/2021, 15:15:26] [SwitchSound] Stopping Sound....
> [06/01/2021, 15:15:27] TypeError: currentSwitch.playProcess.kill is not a function
> at SwitchSoundPlatform.setPowerState (/usr/local/lib/node_modules/homebridge-switchsound/index.js:263:35)
> at Characteristic.emit (events.js:315:20)
> at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
> at Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:652:12)
> at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1461:24
> at Array.forEach ()
> at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1303:10)
> at HAPServer.emit (events.js:315:20)
> at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
> at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:812:12)
> [06/01/2021, 15:15:27] Got SIGTERM, shutting down Homebridge...


does it always happen? If you turn on and turn off contextually from HomeKit what happens?

To be able to understand the problem you should:

1. Send me the switch configuration
2. Enabling the plugin debug parameter, executing a test and send me the debug log.

Could you tell me your Homerbridge and Nodejs version? Do you work with a raspberry?
